services:
  operaton:
    image: operaton/operaton:1.0.0-beta-3-SNAPSHOT
    environment:
      camunda.bpm.run.cors.enabled: true
      camunda.bpm.run.cors.allowed-origins: '*'
    ports:
      - "8084:8080"
  c7:
    image: camunda/camunda-bpm-platform:run-latest
    environment:
      camunda.bpm.run.cors.enabled: true
      camunda.bpm.run.cors.allowed-origins: '*'
    ports:
      - "8088:8080"

